CREATE TABLE AHPATIENT
(

	PATIENTID NUMBER(19,0) NOT NULL,
	IDENTIFICATIONNO VARCHAR2(20) NOT NULL,
	FIRSTNAME VARCHAR2(64), 
	LASTNAME VARCHAR2(64),
	BIRTHDATE DATE,
	GENDER VARCHAR2(1),
	STATUS VARCHAR2(1),
	CONSTRAINT AHPATIENT_PK PRIMARY KEY (PATIENTID)
);
 